backend:
  name: git-gateway
  branch: master
media_folder: public/static/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      
      - label: 'Content Blocks'
        name: 'block'
        widget: 'list'
        types:
          - label: '2-Column Image Set'
            name: '2-column-image'
            widget: 'object'
            fields:
              - { label: 'Column 1 Image', name: 'image-1', widget: 'image', required: true }
              - { label: 'Column 2 Image', name: 'image-2', widget: 'image', required: true }

          - label: '3-Column Image Set'
            name: '3-column-image'
            widget: 'object'
            fields:
              - { label: 'Column 1 Image', name: 'image-1', widget: 'image', required: true }
              - { label: 'Column 2 Image', name: 'image-2', widget: 'image', required: true }
              - { label: 'Column 3 Image', name: 'image-3', widget: 'image', required: true }

          - label: 'Caption & Video Block'
            name: 'caption-video'
            widget: 'object'
            fields:
              - { label: 'Caption Title', name: 'title', widget: 'string', required: true}
              - { label: 'Caption Body', name: 'body', widget: 'markdown'}
              - { label: 'Hosting Platform', name: 'platform', widget: "select", options: ['YouTube', 'Vimeo'], default: ['YouTube'], required: true}
              - { label: 'Video ID', name: 'id', widget: 'string', required: true}

          - label: 'Caption & Image Block'
            name: 'caption-image'
            widget: 'object'
            fields:
              - { label: 'Caption Title', name: 'title', widget: 'string', required: true}
              - { label: 'Caption Body', name: 'body', widget: 'markdown'}
              - { label: 'Image', name: 'image', widget: 'image', required: true}

          - label: 'Image & Quote Block'
            name: 'image-quote'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image', required: true}
              - { label: 'Quote', name: 'quote', widget: 'markdown', required: true}
              - { label: 'Quote Citation', name: 'citation', widget: 'string'}
 
  - label: 'Room'
    name: 'room'
    folder: 'content/rooms'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Room Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - label: 'Project'
    name: 'projects'
    folder: 'content/projects'
    fields:
      - { label: 'Project Name', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Another Property', name: 'property', widget: 'string' }
